# Generated by Django 4.1.4 on 2022-12-14 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ipvisits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=20)),
                ("fecha_visita", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ipVisits",
            },
        ),
        migrations.CreateModel(
            name="Portafolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.TextField()),
                ("titulo_project", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("tags", models.CharField(max_length=100)),
                ("url_github", models.TextField()),
                (
                    "id_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portafolio",
            },
        ),
    ]
